language: java
jdk:
- oraclejdk8
env:
  global:
    secure: S+WQbJdYVXoyzDxt4xBAE9JkzpBteDT4tFO+22lX8raXj/yVFCJiBj4cH30RL8xx/09+j90NAAwDSXqbSreZuNKrFYNekQHguCJMSfDJoiycpuf0rmRfj1ZdOkBOs4oyHY1SNsniYwBK1cRMkePmbtkZ2l9OmPCv/glKjjUOQZ1rMHylzm8Vf3pfOpQVWD1L7UhWmdz/skJjcdDHCJxbMVs6Z2Uxg/h/zMAe35vNlR+BFYIYj2TL0KBfkFKslSPdaautzu3XRdFwL0ZbVwBo7rMItW72h14uRV2ftlkbL4iIT3SylbiNAOBLJ8QEe9+qbT+WeuqYxhwdhQkrsRpoD0M1Xr/AKiPYVvkN32vAk12Q0uakPS/FQJM8vMX7eMtlBPYXBQDExo+Zv+lramqF25UFPe4Ynqa2BWlRstFNa8CNd/xvHcGazl48vI22qlVPmdqipqOIIvYEYKV5v7WoP61ss28vIIYPnaNHzTC2x22UcWhUUqq6/0204esrYFE8NlfctiIpqSqIlQqS/WXArF8hpHpNvLDfE5ViWPBAlODEwgGUsCHqnrAEMilNiIK3v0haDalH8LVC+dPkmQr1oQDwf0jME3s7vN0dJyQsvIGM9nBh5scqfi6BjyDHNSgXa7B8PsjFNK4FnyE7YemfF0K9++/rCV9WLPMPux5vJ88=
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- git config --local user.name "Auto Release"
- git config --local user.email "auto@release.de"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: IntegrationTestclient/libs/*
  skip_cleanup: true
  on:
    tags: true
